### ISSUE TITLE
Phenocarta dumper is no longer working

### ISSUE THREAD

**Issue by stuppie** [stuppie/wdbiothings#2]
@JacobsonMT 
The function to [get the latest release](https://github.com/SuLab/wdbiothings/blob/master/wdbiothings/contrib/phenocarta/dumper.py#L16) is no longer working. Please check when you get a chance. Thanks

**Comment by JacobsonMT** [comment]
Issue should now be fixed. A new release of Gemma modified the RESTful services endpoint without also adding an apache rewrite for the previous url. The [latest release endpoint](http://www.chibi.ubc.ca/Gemma/rest/phenotype/find-all-dumps) should resolve now.
